***Decision Tree Vs Random Forest Regression***

# Importing the libraries

In [0]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#Importing the Dataset

In [13]:
Dataset = pd.read_csv('Dataset.csv')
X = Dataset.iloc[:, :-1].values
Y = Dataset.iloc[:, -1].values
Dataset.head(5)

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56
3  20.86  57.32  1010.24  76.64  446.48
4  10.82  37.50  1009.23  96.62  473.90

In [14]:
print(X)


[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]



# Splitting the dataset into the Training set and Test set

In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2, random_state = 0)

#Training the Decision Tree Regression Model on Dataset

In [16]:
from sklearn.tree import DecisionTreeRegressor
DT = DecisionTreeRegressor(random_state = 0)
DT.fit(X_train, Y_train)

DecisionTreeRegressor(ccp_alpha=0.0, criterion='mse', max_depth=None,
                      max_features=None, max_leaf_nodes=None,
                      min_impurity_decrease=0.0, min_impurity_split=None,
                      min_samples_leaf=1, min_samples_split=2,
                      min_weight_fraction_leaf=0.0, presort='deprecated',
                      random_state=0, splitter='best')

Predicting Test set results

In [17]:
Y_P1 = DT.predict(X_test)
np.set_printoptions(precision=2)
Y_test1 = Y_test.reshape(len(Y_test),1)
print(np.concatenate((Y_P1.reshape(len(Y_P1),1), Y_test1),1))

[[431.28 431.23]
 [462.81 460.01]
 [460.06 461.14]
 ...
 [471.46 473.26]
 [437.76 438.  ]
 [462.55 463.28]]


Decision Tree Regression Model Performance

In [18]:
from sklearn.metrics import r2_score
r2_score(Y_test1, Y_P1)

0.9226091050550043

# Training the Random Forest Regression Model on Dataset

In [19]:
from sklearn.ensemble import RandomForestRegressor
RF = RandomForestRegressor(n_estimators = 10, random_state = 0)
RF.fit(X_train, Y_train)

RandomForestRegressor(bootstrap=True, ccp_alpha=0.0, criterion='mse',
                      max_depth=None, max_features='auto', max_leaf_nodes=None,
                      max_samples=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      n_estimators=10, n_jobs=None, oob_score=False,
                      random_state=0, verbose=0, warm_start=False)

Predicting Test set results

In [20]:
Y_P2 = RF.predict(X_test)
np.set_printoptions(precision=2)
Y_test2 = Y_test.reshape(len(Y_test),1)
print(np.concatenate((Y_P2.reshape(len(Y_P2),1), Y_test2),1))

[[433.78 431.23]
 [457.99 460.01]
 [463.14 461.14]
 ...
 [470.16 473.26]
 [439.51 438.  ]
 [460.32 463.28]]


Random Forest Regression Model Performance

In [21]:
from sklearn.metrics import r2_score
r2_score(Y_test2, Y_P2)

0.9615980699813017